// Note: Autogenerated by TypeWriter from c# classes
// Do not modify here

module App { 
    export class BaseModel { 
    // Inherited properties
    
    // Class properties
    
    public id: string;
    public versionHistory: UpdateModel[];
    }
}

