// Note: Autogenerated by TypeWriter from c# classes
// Do not modify here

module App { $Classes(*Model)[
    export class $Name { 
    // Inherited properties
    $BaseClass[$Properties[
    public $name: $Type;]]
    // Class properties
    $Properties[
    public $name: $Type;]
    }]
}

