// Note: Autogenerated by TypeWriter from c# classes
// Do not modify here

module App { 
    export class UserModel { 
    // Inherited properties
    
    public id: string;
    public versionHistory: UpdateModel[];
    // Class properties
    
    public userName: string;
    public eMail: string;
    }
}

